<?php
    $action = $_POST['action'];
    if ($action == 'getclothtype') {
    $allcategorytype = array(
        'select'=>'--select--',
        'Tops' => [
            '--select--',
            'Asymmetric',
            'Blouse Tops',
            'Bardot Top',
            'Boxy Top',
            'Batwing Tops',
            'Crop Top',
            'Camisole Tops',
            'Collar Top',
            'Choker Top',
            'Cropped strappy top',
            'Cape Top',
            'Cold Shoulder Top',
            'Cinched Waist Top',
            'Exaggerated sleeve tops',
            'Floral Top',
            'Flared Tops',
            'Garnet Top',
            'Kaftan Top',
            'Maxi Top',
            'Shirt Style Top',
            'Scarf Top',
            'Peplum Top',
            'One shoulder Top',
            'Tube Top',
            'Tank Top',
            'Tunic Top',
            'Wrap Tops',
        ],'Blouses' => [
            '--select--',
            'Backless blouse',
            'Cold Shoulder Blouse',
            'Boat neck',
            'Collared Blouse',
            'Halter Neck Blouse',
            'Round Neck Blouse',
            'Cape Blouse',
            'Lace Blouse',
            'Long blouse',
            'Peplum Blouse',
            'Asymmetrical Blouse',
            'Babydoll Blouse',
            'Princess cut blouse',
            'Scoop Neck Blouse',
            'Kalamkari blouses',
            'Mirror Blouse',
        ],'Coat' => [
            '--select--',
            'Trench coat',
            'Anorak',
            'Chesterfield',
            'Overcoat',
            'Peacoat',
            'Raincoat',
            'Duffle coat',
            'Mac coat',
            'Shearling coat',
            'Frock coat',
            'Alpaca Coat',
            'Cape Coat',
            'Lapel Coat',
            'over coat',
            'Blazer',
            'Cashmere coats',
            'Evening Coat',
        ],'Jacket' => [
            '--select--',
            'Denim Jacket',
            'Leather jacket',
            'Puffer Jacket',
            'Trench coat',
            'Bomber Jacket',
            'Motorcycle Jacket',
            'Parka',
            'Field Jacket',
            'Faux Fur Jacket',
            'Puffer Jacket',
            'Cropped Jacket',
            'chanel jacket',
            'Bolero jacket',
            'Anorak jacket',
        ],'Crop Top' => [
            '--select--',
            'Layered crop top',
            'Bardot Crop Tops',
            'Lace Crop Top',
            'Smocked Crop Top',
            'Black Striped Top',
            'Choker Top',
            'Fringe Crop Top',
            'Cold Shoulder Top',
            'Henley Crop Top',
            'Collar Top',
            'MOCK NECK CROP TOP',
            'PRIDE CROCHET BRA CROP TOP',
            'ONE SHOULDER TANK CROP TOP',
            'CELESTIAL STRETCH CROP TOP',
            'V NECK CROP TOP',
            'STRAPLESS CROP TOP',
        ],'Shirt' => [
            '--select--',
            'Check Stylish Shirts',
            'Ladies Casual ',
            'Formal Shirts',
            'Bohemian-Style Printed Crop Shir',
            'Stylish White Shirts',
            ' Hawaiian Collar Satin Shirt ',
            'Sleeveless Latest Ladies Shirt',
            'Stylish Long Shirts',
            'Party-wear Latest Shirts',
            'Vintage-style Shirts',
            'Denim Shirt',
            'Linen Shirt',
            ' Ruffle Front Shirts',
            ' Sleeve Shirts',
            'Puffed Sleeve Shirts',
            'Tie-up Shirts ',
            'Printed Cotton Shirt ',
        ],'Lingerie' => [
            '--select--',
            'Bikini Underwear',
            'Bodysuit',
            'Bralette',
            'Bustier',
            'Camisole',
            'Chemise/Babydoll',
            'Corset',
            'Garter or Suspender Belt',
            'Hipster',
            'Robe',
            'Romper',
            'Tap Short',
            'Thong',
        ],
        'Bra' => [
            '--select--',
            'T-shirt Bra',
            'Multiway Bra',
            'Padded Bra',
            'Push-up Bra',
            'Underwired Bra',
            'Strapless Bra ',
            'Balconette Bra',
            'Front Open Bra',
            'Racerback Bra',
            'Nursing Bra',
            'Halter Bra',
            'Bandeau Bra',
            'Sports Bra',
            'Stick on Bra',
            'Plunge Bra',
            'Bridal Bras',
            'Non-Padded bras',
            'Cage Bras',
            'Lace Bra',
            'Wireless Bra',
            'Bralette',
            'Seamless Bra',
            'Demi Bras',
            'Full Figure bras',
            'Transparent Bra',
            'Beginner Bra',
        ],'Hoodie' => [
            '--select--',

            'Lace-up Hoodie',
            'Faux Fur Hoodie',
            'Cropped Hoodie',
            'Cut-Sleeved Hoodie',
            'Graphic Hoodie',
            'Colour-Blocked Hoodie',
        ],
        'Sheath Dress' => [
            '--select--',

            'Classic Sheath',
            'Wrap Sheath',
            'Shift Sheath',
            'Bodycon Sheath',
            'Midi Sheath',
            'Sleeveless Sheath',
            'Cap Sleeve Sheath',
            'Bell Sleeve Sheath',
            'Off-shoulder Sheath',
            'Lace Sheath',
        ],
        'Cloak' => [
            '--select--',
            'Cape',
            'Poncho',
            'Bathrobe',
            'Capuchin',
            'Mantle',
            'Capelet',
            'Capote',
            'Cardinal',
            'Kinsale Cloak',
            'Shawl',
            'Burnoose',
            'Domino',
            'Frock',
            'Pelisse',
            'Sarape',
            'Abolla',
            'Afghan ',
            'Blanket',
            'Buka cloak',
            'Chlamys',
            'Dolman',
        ],
        'Camisole' => [
            '--select--',
            'Body Hugging',
            'Cotton Camisole',
            'Silk',
            'Lace Cami',
            'Camisole Bra',
            'Shapewear',
            'Plus-Size Camisole',
            'Camisole Tops',

        ],
        'Mini' => [
            '--select--',
            'Bandage dress',
            'Blazer dress',
            'Bodycon',
            'Mini kimono dress',
            'Mini qipao dress',
            'Mini sundress',
            'Pouf dress',
            'Shirtdress',
            'Sweater dress',
            'T-shirt dress',
            'A-line Dress',
            'Halter Dress',
            'Skater',
            'Skater',
            'Smock Dress',
            'Wrap Dress',
            'Babydoll Dress',
            'Cocktail dress',
            'Tent Dress',
            'Slip dress',
            'Asymmetrical Dress',
        ],'Co-ord Set' => [
            '--select--',
            'Deconstructed Set',
            'Classic Skirt & Top Set',
            ' Up-Cycled Set',
            'Versatile Kurta & Pants Set',
            'Lehenga',
            'Kurta-Jacket Set',
            ' Kurta & Skirt Set',
            'Top & Skirt Co-ord Set',
            'Essential Crop Top & Palazzo Set',
        ],
    );
    $clothname=$_POST['clothsval'];
    $output="";
   foreach ($allcategorytype as $key => $clothstype) {
    if ($clothname==$key) {
       foreach ($clothstype as $value) {
        $output.= " <option>$value</option>";
       }
        echo $output;
    }
   }
        
    }else{
        echo "no";
    }
?>
